"""first

Revision ID: 4a302afcc22a
Revises: 
Create Date: 2021-11-26 00:21:50.181399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a302afcc22a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Note',
    sa.Column('idNote', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('text', sa.String(length=20), nullable=False),
    sa.Column('idOwner', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('idNote')
    )
    op.create_table('Tag',
    sa.Column('idTag', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('idTag')
    )
    op.create_table('NoteStatistics',
    sa.Column('time', sa.String(length=20), nullable=False),
    sa.Column('idNote', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idNote'], ['Note.idNote'], ),
    sa.PrimaryKeyConstraint('idNote')
    )
    op.create_table('User',
    sa.Column('idUser', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=20), nullable=False),
    sa.Column('Tag_idTag', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Tag_idTag'], ['Tag.idTag'], ),
    sa.PrimaryKeyConstraint('idUser')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User')
    op.drop_table('NoteStatistics')
    op.drop_table('Tag')
    op.drop_table('Note')
    # ### end Alembic commands ###
